### ISSUE TITLE
Add Sidebar on Homepage

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/tvhwdsb-theme#10]
Currently the My Videos and My Playlists links are somewhat hidden under the Adminbar/Buddypress profile links. Now that Playlists are possible, I think it would be helpful to add a sidebar on the homepage to make it easier for users to be able to find the content they have created on the VP. A sidebar on the homepage would allow for a widget with the links to these items. 

The sidebar CSS and most of the formatting is there, but it's not loaded on the homepage. I've tried to go into the functions.php file and adding this, which is basically how the sidebar is being called for is_singular, but I'm obviously missing something. Any help would be appreciated: 

````
/**
 * Enqueue sidebar on home page
 */

function hwdsb_tv_enqueue_sidebar () {
	if ( is_home() && is_active_sidebar( 'sidebar-1' ) ) {
		wp_enqueue_script( 'gazette-sidebar', get_template_directory_uri() . '/js/sidebar.js', array(), '20150429', true );
}
}
add_action( 'wp_enqueue_scripts', 'hwdsb_tv_enqueue_sidebar' );
````

**Comment by mrjarbenne** [comment]
I also added the `<?php get_sidebar(); ?>` into content.php thinking that was the missing piece, but that didn't seem to do it either.

**Comment by r-a-y** [comment]
I think adding the links to the sidebar wouldn't be that great aesthetically.

What about adding some links to the top menu?  Like so:
![GIF of logged-in links in top menu](https://cloud.githubusercontent.com/assets/505921/22418300/4f06d05a-e68d-11e6-9598-67aa4316398c.gif)

We could change the hamburger three-lines icon to somethng else if we wanted to.  Also, I think it would be neat if we switched out the "hwdsb.tv" text with an inverted blue-on-white version of the current logo.

**Comment by mrjarbenne** [comment]
I was wondering that as I was doing it, that I might just be wrecking the front page by throwing a sidebar on. 

I love both those ideas. Hamburger seems pretty universal (can't think of another button icon that would fit, but open to suggestions if you have one)

Thanks for the better fix.

**Comment by mrjarbenne** [comment]
Actually. Looking at this a bit further, putting those items under a Hamburger icon will result in two burgers on smaller screens (the main menu already collapses into that icon.)

Can we Add My Videos and My Playlists directly to the menu, like the Upload button? I can combine the Channel links on the nav menu into one menu, to open up some real estate.

![2017-01-30_11-30-26](https://cloud.githubusercontent.com/assets/480667/22431507/b941edc2-e6df-11e6-8cf6-90826031175f.png)
