### ISSUE TITLE
User Playlist Archive Only Displays # of Posts set in Settings/Reading

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/tvhwdsb-theme#11]
When a user navigates to their Playlist page (eg: https://hwdsb.tv/author/jarbenne/playlists/) the number of playlists they can see is limited to the number of posts appearing on the main page under Settings/Reading. (eg: I only see 6 playlists, without an option to view additional playlists)

The Playlists page doesn't have pagination options to view additional posts, although I don't necessarily think that's the appropriate fix. When viewing one's playlists, the view could match that of a list of videos within the playlist, which loads them all on the single screen.

**Comment by r-a-y** [comment]
All playlists should now be shown when you navigate to a user's playlists page.
