### ISSUE TITLE
Sharing buttons don't show up on unlisted posts

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/tvhwdsb-theme#12]
The Share tab on Unlisted videos is not displaying the Social Warfare buttons under the share tab. I think this changed when the playlist tab was added.

![2017-01-30_13-29-04](https://cloud.githubusercontent.com/assets/480667/22435963/14987280-e6f0-11e6-8907-1dba70873498.png)

**Comment by r-a-y** [comment]
It's a problem with Social Warfare.  They added a check to only render their buttons on public posts in a recent update.

Will see what I can do here.
