### ISSUE TITLE
Changed Some Colours

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/tvhwdsb-theme#2]
We haven't both been developing at the same time before (wheeeeeee), so I'm not going to overwrite the server with this change just made on Github. Are you developing elsewhere and pushing to Github? Is it safe for me to be making changes over here? 

https://github.com/hwdsbcommons/tvhwdsb-theme/commit/566a1791d7b4cae3554a5f82fd804de4dbc03dde

**Comment by r-a-y** [comment]
That's what Git is for! :)

Feel free to commit changes.
