### ISSUE TITLE
Featured Images

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/tvhwdsb-theme#6]
Featured Videos, and Related Videos, require a Featured Thumbnail Image.

**Comment by mrjarbenne** [comment]
Perhaps this could be tweaked to help: https://wordpress.org/plugins/automatic-featured-images-from-videos/

The issue is the video doesn't actually appear in the cpt edit area in the dashboard

**Comment by r-a-y** [comment]
I'd probably use this approach instead:
https://jetpack.com/2013/10/15/add-a-default-fallback-image-if-no-image/

And follow how we're already displaying the thumbnail on archive pages.

**Comment by mrjarbenne** [comment]
Cool. It looks like that will cover both cases. I was looking at this, but it's just for related images. 

https://jetpack.com/support/related-posts/customize-related-posts/#default-image

**Comment by mrjarbenne** [comment]
@r-a-y I think I have this set up right, but the thumbnail isn't rendering. Any chance we are blocking thumbnails in lieu of vimeo thumbs? 

~~That said, in the Media library on the main site images aren't loading either: might be related.~~

Edit: the s3 uploads plugin was acting up. Sorted that out. Related images still not loading. I've probably missed something simple.

**Comment by mrjarbenne** [comment]
Perhaps related: https://core.trac.wordpress.org/ticket/18302

I might not be able to use a URL like /images/hwdsbtv-preview-image.png in a child theme.

**Comment by mrjarbenne** [comment]
Related commit: https://github.com/hwdsbcommons/tvhwdsb-theme/commit/59f8f5a425edd4ea35bdb969bc8efd71ecdffd68

**Comment by mrjarbenne** [comment]
Ok. I definitely can't call the URL directly. I need to switch out to something like this:

`<?php echo get_template_directory_uri(); ?>/images/hwdsbtv-preview-image.png" />`

Getting closer....

**Comment by mrjarbenne** [comment]
Got this from the Calling Jetpack Photon URL safely: https://jetpack.com/2013/07/11/photon-and-themes/

**Comment by mrjarbenne** [comment]
A fallback URL was only half the ticket. The other half I'll leave to @r-a-y, who forged the initial code that brings Vimeo thumbnails to the archives.

> And follow how we're already displaying the thumbnail on archive pages.

**Comment by mrjarbenne** [comment]
- [x] snag thumbnails from vimeo
- [x] Add featured image functionality on homepage to support vp_video
  
  `add_theme_support( 'featured-content', array(
    'filter'     => 'mytheme_get_featured_posts',
    'max_posts'  => 20,
    'post_types' => array( 'post', 'page', 'vp_video' ),
  ) );`

Need this to work without giant featured images appearing on single video page

![featured image](https://cloud.githubusercontent.com/assets/480667/15811536/adbbd810-2b77-11e6-99d7-3aec6f75e294.gif)

**Comment by r-a-y** [comment]
Fallback image should work correctly now.

As for featured image, I'm not sure what this functionality is all about.  Can you elaborate?  What are we trying to do?

**Comment by mrjarbenne** [comment]
Check out the demo of the theme we are using here: https://gazettedemo.wordpress.com/

It offers up the ability to feature 6 posts more prominently above the menu bar. On the Mediacore site this was a slider we could populate. I'm looking to do the same thing here, only with vp_video post type. 

I think we will also have to omit the featured image functionality from our single content page, as it ends up firing a Hero sized featured image/video in lieu of the regular image.

**Comment by mrjarbenne** [comment]
That looks awesome.
