### ISSUE TITLE
Related videos should go in the sidebar

### ISSUE THREAD

**Issue by r-a-y** [hwdsbcommons/tvhwdsb-theme#8]
@mrjarbenne - What are you thoughts as to moving the JetPack related videos block to the sidebar?

The reason I ask is I implemented a tabbed container on single video pages and the related videos block is currently being rendered in the "About" tab due to the way I'm using `the_content()`.

Or we could just move the related videos block underneath the tabbed container.

**Comment by mrjarbenne** [comment]
I'm good with that. I believe YouTube has it on the sidebar so that will be a familiar layout for users.

**Comment by mrjarbenne** [comment]
I'm not seeing this in the sidebar. I thought it was hardcoded, or does it require a specific Widget to be added to the sidebar that I'm missing?

**Comment by r-a-y** [comment]
Did you configure Jetpack's Related Posts module properly?  I'm not sure how that works, but I think it makes a copy of the post to the wp.com servers.  Have you synced up all the posts?  Perhaps it only works for public posts.

**Comment by mrjarbenne** [comment]
Ugh. Sorted it out.
