### ISSUE TITLE
Remove top banner on single video pages

### ISSUE THREAD

**Issue by r-a-y** [hwdsbcommons/tvhwdsb-theme#9]
@mrjarbenne - Should we remove the large banner logo on single video pages?  Or we can remove it on larger screen resolutions only.

**Comment by mrjarbenne** [comment]
I'm away for a couple of days with only my phone so I can't see the big screen render. I'm good with hiding it on single video pages.

**Comment by mrjarbenne** [comment]
Just checked this out. Looks so much better. Good call.
